import streamlit as st
from ultralytics import YOLO
from PIL import Image
import numpy as np
import pandas as pd
import cv2
import math
from fpdf import FPDF
from datetime import datetime

# دالة ال PDF
# دالة ال PDF المحدثة (مضادة للانهيار)
def create_ast_pdf(patient_name, sample_id, bacteria_name, report_data):
    pdf = FPDF()
    pdf.add_page()
    
    # دالة صغيرة لتنظيف أي نص من الحروف العربي أو الإيموجيز عشان FPDF ميضربش
    def clean_text(text):
        if text is None:
            return ""
        return str(text).encode('latin-1', 'ignore').decode('latin-1')

    # تنظيف المدخلات
    patient_name_clean = clean_text(patient_name)
    if not patient_name_clean and patient_name: 
        # لو كتب الاسم كله عربي واتفلتر، هنكتب الجملة دي بدل ما نسيبها فاضية
        patient_name_clean = "Arabic Name (Unsupported in PDF)"
    elif not patient_name_clean:
        patient_name_clean = "Unknown Patient"
        
    sample_id_clean = clean_text(sample_id)
    bacteria_name_clean = clean_text(bacteria_name)

    # 1. Header (Lab Name & Logo text)
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "BactoVision(TM) - Clinical Laboratory Report", ln=True, align='C')
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 10, "Powered by SCOPE AI", ln=True, align='C')
    pdf.line(10, 30, 200, 30)

    # 2. Patient & Sample Info
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(35, 8, "Patient Name:", 0, 0)
    pdf.set_font("Arial", '', 11)
    pdf.cell(85, 8, patient_name_clean, 0, 0)

    pdf.set_font("Arial", 'B', 11)
    pdf.cell(30, 8, "Date:", 0, 0)
    pdf.set_font("Arial", '', 11)
    pdf.cell(40, 8, datetime.now().strftime("%Y-%m-%d %H:%M"), 0, 1)

    pdf.set_font("Arial", 'B', 11)
    pdf.cell(35, 8, "Sample ID:", 0, 0)
    pdf.set_font("Arial", '', 11)
    pdf.cell(150, 8, sample_id_clean, 0, 1)

    pdf.line(10, 55, 200, 55)
    pdf.ln(5)

    # 3. Diagnosis
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(180, 0, 0) # لون أحمر داكن لاسم البكتيريا
    pdf.cell(0, 10, f"Isolated Pathogen: {bacteria_name_clean}", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # 4. AST Table Header
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(20, 10, "Disk", 1, 0, 'C')
    pdf.cell(80, 10, "Antibiotic", 1, 0, 'C')
    pdf.cell(35, 10, "Zone (mm)", 1, 0, 'C')
    pdf.cell(55, 10, "Interpretation", 1, 1, 'C')

    # 5. AST Table Data
    pdf.set_font("Arial", '', 11)
    for row in report_data:
        disk_num = str(row['Disk Number']).replace("🟢", "").replace("🟡", "").replace("🔴", "").replace("🔵", "").replace("🟣", "").strip()
        disk_num = clean_text(disk_num)
        
        antibiotic_clean = clean_text(row['Antibiotic'])
        zone_clean = clean_text(row['Diameter (mm)'])
        
        pdf.cell(20, 10, disk_num, 1, 0, 'C')
        pdf.cell(80, 10, antibiotic_clean, 1, 0, 'C')
        pdf.cell(35, 10, zone_clean, 1, 0, 'C')
        
        status = str(row['Clinical Status'])
        
        # تنظيف النص من الإيموجيز قبل الطباعة
        clean_status = status.replace("✅", "").replace("❌", "").replace("⚠️", "").replace("⏳", "").strip()
        clean_status = clean_text(clean_status)
        
        # تلوين النتيجة (S أخضر، R أحمر، I أصفر داكن)
        if "Sensitive" in status:
            pdf.set_text_color(0, 128, 0)
        elif "Resistant" in status:
            pdf.set_text_color(255, 0, 0)
        else:
            pdf.set_text_color(204, 153, 0)
            
        # هنطبع النص النظيف 
        pdf.cell(55, 10, clean_status, 1, 1, 'C')
        pdf.set_text_color(0, 0, 0) # نرجع اللون أسود تاني

    # 6. Footer Disclaimer
    pdf.ln(15)
    pdf.set_font("Arial", 'I', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, "This report was automatically generated by the BactoVision CDSS pipeline.", ln=True, align='C')
    pdf.cell(0, 5, "Please consult a clinical microbiologist or physician for final therapeutic decisions.", ln=True, align='C')

    # تحويل الـ PDF لـ bytes 
    return pdf.output(dest='S').encode('latin1')

# ==========================================
# 1. إعدادات الصفحة واللوجو والموديلات
# ==========================================
# 1. قراءة صورة الأيقونة المربعة
favicon = Image.open("icon.png")

# 2. إعدادات الصفحة (شيلنا علامات التنصيص من حوالين كلمة favicon)
st.set_page_config(page_title="BactoVision™ | SCOPE AI", page_icon=favicon, layout="wide")

# 2. اللوجو في السايد بار (استخدمنا width=220 عشان نصغره شوية بدل ما ياخد العرض كله)
col_sidebar1, col_sidebar2, col_sidebar3 = st.sidebar.columns([0.5, 3, 0.5])
with col_sidebar2:
    st.image("logo_white2.png", width="stretch")
st.sidebar.markdown("---") 

# 3. الصفحة الرئيسية (استخدمنا clamp عشان الخط يصغر أوتوماتيك على الموبايل وميكسرش الكلمة)
st.markdown("<div style='text-align: center; font-size: clamp(2rem, 8vw, 4rem); font-weight: bold; margin-bottom: 0px; white-space: nowrap;'>BactoVision™</div>", unsafe_allow_html=True)

# 4. الجملة الأكاديمية (قربناها من العنوان عشان شكلهم يبقى متماسك)
st.markdown("<p style='text-align: center; color: #a0a0a0; font-size: 1.2rem; margin-top: -10px;'>Powered by SCOPE AI (Smart Colony Object Processing & Enumeration)</p>", unsafe_allow_html=True)
st.markdown("---")

# لوحة التحكم
with st.sidebar:
    st.header("Engine Configuration")
    conf_threshold = st.slider("Confidence Threshold", min_value=0.1, max_value=0.9, value=0.5, step=0.05)
    iou_threshold = st.slider("IoU (Overlap) Filter", min_value=0.1, max_value=0.9, value=0.35, step=0.05)
    
    st.divider()
    
    st.header("Display Settings")
    hide_labels = st.checkbox("Hide Labels (Clean View)", value=False)
    label_size = st.slider("Label Text Size", min_value=5, max_value=100, value=20, step=1)
    box_thickness = st.slider("Box Thickness", min_value=1, max_value=10, value=2, step=1)
    
    st.divider()
    
    # الزرار السحري الجديد
    st.header("Advanced Analysis")
    tta_mode = st.checkbox("Enable Deep Scan (TTA)", value=False, help="Activates test-time augmentation for maximum precision (1024 resolution) on crowded plates.")
    
    st.divider()
    
    # أدوات المعالجة القديمة بتاعتنا
    st.header("Image Processing")
    denoise = st.checkbox("Denoise (Remove WhatsApp Pixels)", value=False)
    contrast = st.slider("Contrast", min_value=0.5, max_value=3.0, value=1.0, step=0.1)
    brightness = st.slider("Brightness", min_value=-50, max_value=50, value=0, step=5)
    
    st.divider()
    st.markdown("""
**Capital University** 
* Faculty of Science.
* Biotechnology Department.
""")
    
    st.markdown("""
**Developed by Our Team:**
* Yousef Abdel Haseeb
* Gerges Fouad
* Mohamed Ibrahim
* Mohamed Ashraf
* Mohamed Marwan
* Seif El-Din Omar
""")

@st.cache_resource
def load_models():
    detector = YOLO('best.pt')         
    gatekeeper = YOLO('gatekeeper.pt') 
    ast_segmenter = YOLO('ast_model.pt')
    return detector, gatekeeper, ast_segmenter

detector_model, gatekeeper_model, ast_model = load_models()

# ==========================================
# قاعدة البيانات الطبية للمضادات الحيوية (CDSS Guidelines)
# ==========================================
ANTIBIOTIC_GUIDE = {
    "P.aeruginosa": {
        "Recommended": {
            "Fluoroquinolones": ["Ciprofloxacin (CIP)", "Levofloxacin (LEV)"],
            "Antipseudomonal Penicillins": ["Piperacillin-Tazobactam (TZP)", "Ticarcillin-Clavulanate (TIM)"],
            "Cephalosporins (Antipseudomonal)": ["Ceftazidime (CAZ)", "Cefepime (FEP)"],
            "Carbapenems": ["Meropenem (MEM)", "Imipenem (IPM)"],
            "Aminoglycosides": ["Amikacin (AK)", "Gentamicin (CN)", "Tobramycin (TOB)"]
        },
        "Resistant": {
            "Standard Penicillins": ["Ampicillin (AMP)", "Amoxicillin-Clavulanate (AMC)"],
            "Macrolides": ["Erythromycin (E)", "Azithromycin (AZM)", "Clarithromycin (CLR)"],
            "Tetracyclines": ["Tetracycline (TE)", "Doxycycline (DO)"],
            "1st/2nd Gen Cephalosporins": ["Cefazolin (KZ)", "Cefuroxime (CXM)", "Cefotaxime (CTX)"],
            "Others": ["Trimethoprim-Sulfamethoxazole (SXT)", "Chloramphenicol (C)"]
        }
    },
    "E.coli": {
        "Workflow": {
            "1. Initial ESBL Screen (Beta-Lactamase Check)": "Test with Amoxicillin vs. Amoxicillin-Clavulanate (AMC). If the inhibition zone increases significantly with the addition of Clavulanic Acid (Beta-lactamase inhibitor), suspect ESBL production.",
            "2. AmpC Screening": "Test with Cefoxitin (FOX). If the isolate is Resistant to FOX ➡️ Suspect AmpC production (as AmpC beta-lactamases are not inhibited by Clavulanate and confer resistance to Cefoxitin).",
            "3. AST Interpretation (If ESBL ONLY)": "If the isolate is ESBL positive (AmpC negative): It will show SENSITIVITY to Cephamycins (e.g., Cefoxitin), Carbapenems, and Beta-lactam/inhibitor combinations. All other Penicillins and 1st-3rd Gen Cephalosporins MUST be reported as RESISTANT.",
            "4. AST Interpretation (If AmpC POSITIVE)": "If AmpC producing: It will show RESISTANCE to Cephamycins (Cefoxitin) and most Beta-lactam/inhibitor combinations (e.g., AMC). It typically remains SENSITIVE to 4th Gen Cephalosporins (Cefepime - FEP) and Carbapenems."
        },
        # التقسيمة الجديدة للحالات الـ 4
        "Phenotypes": {
            "1️⃣ ESBL Only": {
                "✅ Sensitive (S)": ["Penicillins + combinations", "cephamycins", "Carbapenems", "polymyxins"],
                "⚠️ Variable / Intermediate": ["Penicillins + combinations", "Cefepime (SDD/I)", "Aminoglycosides", "Fluoroquinolones", "Tetracyclines"],
                "❌ Resistant (R)": ["Penicillins", "1st-3rd-4th-5th Gen Cephalosporins", "monobactams"]
            },
            "2️⃣ AmpC Only": {
                "✅ Sensitive (S)": ["Cefepime", "Carbapenems", "polymyxins"],
                "⚠️ Variable / Intermediate": ["monobactams", "Aminoglycosides", "Fluoroquinolones", "Tetracyclines"],
                "❌ Resistant (R)": ["Resistant to all Beta-lactams (including Cephamycins like Cefoxitin)","Except Carbapenems and Cefepime"]
            },
            "3️⃣ ESBL + AmpC": {
                "✅ Sensitive (S)": ["Carbapenems", "polymyxins"],
                "⚠️ Variable / Intermediate": ["Aminoglycosides", "Fluoroquinolones", "Tetracyclines"],
                "❌ Resistant (R)": ["Penicillins", "Penicillins + combinations", "Cephalosporins", "monobactams"]
            },
            "4️⃣ Neither ESBL nor AmpC": {
                "✅ Sensitive (S)": ["monobactams", "Penicillins + combinations", "cephalosporins", "Carbapenems", "polymyxins"],
                "⚠️ Variable / Intermediate": ["Aminoglycosides", "Fluoroquinolones", "Tetracyclines"],
                "❌ Resistant (R)": ["(Depends on specific strain mechanisms)"]
            }
        }
    },
    "S.aureus": {
        "Workflow": {
            "1. Beta-Lactamase Check": "Check presence of beta-lactamase enzyme by Penicillin. If Penicillin is (R), it confirms beta-lactamase production.",
            "2. MRSA Screen": "Check Cefoxitin susceptibility. Cefoxitin (S) = MSSA. Cefoxitin (R) = MRSA (Force Override: All Beta-lactams are Resistant).",
            "3. Inducible Resistance (D-Test)": "If Erythromycin (R) and Clindamycin (S), perform D-Zone Test.",
            "4. Vancomycin Alert": "Do NOT use disk diffusion for Vancomycin. Use MIC."
        },
        "Phenotypes": {
            "1️⃣ MSSA (Methicillin-Susceptible / Cefoxitin-S)": {
                "✅ Sensitive (S)": ["stable Penicillins","Penicillins + combinations", "Cephalosporins", "Carbapenems", "Glycopeptides", "Lipopeptides", "Oxazolidinones"],
                "⚠️ Variable / Intermediate": ["Macrolides + lincosamide (Check D-Test)", "Fluoroquinolones", "Tetracyclines", "Aminoglycosides"],
                "❌ Resistant (R)": ["Penicillins", "Ampicillin (Typically >90% of strains)"]
            },
            "2️⃣ MRSA (Methicillin-Resistant / Cefoxitin-R)": {
                "✅ Sensitive (S)": ["Vancomycin (MIC <= 2)", "Linezolid", "Daptomycin", "Ceftaroline (5th Gen Cephalosporin)", "Antifolate +DHFR inhibitors"],
                "⚠️ Variable / Intermediate": ["Macrolides + lincosamide (Check D-Test)", "Aminoglycosides", "Tetracyclines"],
                "❌ Resistant (R)": ["ALL Penicillins", "ALL Cephalosporins (1st-4th Gen)", "ALL Carbapenems", "Cefoxitin"]
            },
            "3️⃣ VRSA / VISA (Critical Alert - MIC Only)": {
                "✅ Sensitive (S)": ["Linezolid", "Daptomycin", "Tigecycline", "Antifolate +DHFR inhibitors"],
                "⚠️ Variable / Intermediate": ["Macrolides + lincosamide (Check D-Test)", "Aminoglycosides", "Tetracyclines"],
                "❌ Resistant (R)": ["Vancomycin (VRSA: MIC >= 16 ug/mL)", "ALL Beta-lactams (If MRSA co-expressed)"]
            }
        }
    },
    "B.subtilis": {
        "Workflow": {
            "1. Clinical Significance Check": "Evaluate if the isolate is a true pathogen or environmental contaminant.",
            "2. Beta-Lactamase Production": "Bacillus species inherently produce beta-lactamases. Penicillins and most Cephalosporins are unreliable and should generally be considered resistant.",
            "3. Primary Therapy": "If true infection is confirmed, rely on Glycopeptides, Fluoroquinolones, or Carbapenems."
        },
        "Phenotypes": {
            "1️⃣ Standard Isolate (Family-Based Susceptibility)": {
                "✅ Sensitive (S)": [
                    "Glycopeptides", 
                    "Oxazolidinones", 
                    "Lipopeptides", 
                    "Aminoglycosides", 
                    "Fluoroquinolones", 
                    "Tetracyclines", 
                    "Carbapenems", 
                    "Phenicols", 
                ],
                "⚠️ Variable / Intermediate": [
                    "Aminopenicillins", 
                    "Penicillin/β-lactamase inhibitor combinations", 
                    "Stable penicillins", 
                    "Cephalosporins (Unreliable)", 
                    "Macrolides", 
                    "Lincosamides", 
                    "Antifolate +DHFR inhibitors"
                ],
                "❌ Resistant (R)": [
                    "Penicillins (General)", 
                    "Cephalosporins (General)"
                ]
            }
        }
    },
    "C.albicans": {
        "Workflow": {
            "1. Biological Alert": "Candida is a yeast (fungus), NOT a bacterium. ALL antibacterial agents are inherently INEFFECTIVE.",
            "2. Treatment Strategy": "Antifungal selection depends primarily on the SITE of infection (Systemic vs. Mucosal) and SEVERITY.",
            "3. Resistance Alert": "If the strain is Fluconazole-resistant, switch immediately to Voriconazole or Echinocandins."
        },
        "Phenotypes": {
            "1️⃣ Systemic Infections (Blood/Sterile Fluid)": {
                "✅ Sensitive (S)": [
                    "Echinocandins (e.g., Caspofungin) - Preferred for Critical/Unstable cases", 
                    "Triazoles (e.g., Fluconazole) - Preferred for Stable cases"
                ],
                "⚠️ Variable / Intermediate": [
                    "Liposomal Amphotericin B (Alternative for intolerance) Use with Caution Alternative"
                ],
                "❌ Resistant (R)": [
                    "ALL Antibacterial Agents", 
                    "Topical Antifungals (Nystatin/Clotrimazole - Poor systemic absorption)"
                ]
            },
            "2️⃣ Mucocutaneous Infections (Oral/Vaginal/Skin)": {
                "✅ Sensitive (S)": [
                    "Topical Polyenes (Nystatin) - Preferred for Oral Thrush", 
                    "Topical Azoles (Clotrimazole) - Preferred for Vaginal/Cutaneous"
                ],
                "⚠️ Variable / Intermediate": [
                    "Oral Fluconazole (Reserve for severe or recurrent cases)"
                ],
                "❌ Resistant (R)": [
                    "ALL Antibacterial Agents", 
                    "Systemic Echinocandins (Unnecessary Overkill)"
                ]
            },
            "3️⃣ Refractory / Fluconazole-Resistant": {
                "✅ Sensitive (S)": [
                    "Triazoles Alternative (Voriconazole)", 
                    "Polyenes (Liposomal Amphotericin B) - For Treatment Failure",
                    "Echinocandins (Caspofungin)"
                ],
                "⚠️ Variable / Intermediate": [
                    "Other alternative azoles (e.g., Posaconazole)"
                ],
                "❌ Resistant (R)": [
                    "Fluconazole", 
                    "ALL Antibacterial Agents"
                ]
            }
        }
    }
}
#دالة سحب الادوية 
def get_clinical_recommendations(detected_bacteria_list):
    recs = []
    for bac in detected_bacteria_list:
        if bac in ANTIBIOTIC_GUIDE:
            if "Recommended" in ANTIBIOTIC_GUIDE[bac]:
                # تجميع العائلات الموصى بها للـ P.aeruginosa
                drugs = []
                for family_drugs in ANTIBIOTIC_GUIDE[bac]["Recommended"].values():
                    drugs.extend(family_drugs)
                recs.append(f"[{bac}] Test Panel: {', '.join(drugs)}")
            elif "Phenotypes" in ANTIBIOTIC_GUIDE[bac]:
                # بناخد الأدوية الحساسة من أول حالة (زي הـ MSSA) كبداية مبدئية لحد ما يتعمل AST
                first_pheno = list(ANTIBIOTIC_GUIDE[bac]["Phenotypes"].keys())[0]
                drugs = ANTIBIOTIC_GUIDE[bac]["Phenotypes"][first_pheno].get("✅ Sensitive (S)", [])
                recs.append(f"[{bac}] Primary Panel: {', '.join(drugs)}")
    return " | ".join(recs) if recs else "No baseline data"

# ==========================================
# قاعدة بيانات القياسات الرقمية (AST Breakpoints in mm)
# ==========================================
AST_BREAKPOINTS = {
    "E.coli": {
        "SAM": {"name": "Ampicillin/Sulbactam", "R": 11, "S": 15},
        "AMC": {"name": "Amoxicillin/Clavulanate", "R": 13, "S": 18},
        "TZP": {"name": "Piperacillin/Tazobactam", "R": 17, "S": 21},
        "CTX": {"name": "Cefotaxime", "R": 22, "S": 26},
        "CRO": {"name": "Ceftriaxone", "R": 19, "S": 23},
        "CAZ": {"name": "Ceftazidime", "R": 17, "S": 21},
        "FEP": {"name": "Cefepime", "R": 18, "S": 25},
        "FOX": {"name": "Cefoxitin", "R": 14, "S": 18},
        "CPD": {"name": "Cefpodoxime", "R": 17, "S": 21},
        "ATM": {"name": "Aztreonam", "R": 17, "S": 21},
        "ETP": {"name": "Ertapenem", "R": 18, "S": 22},
        "IPM": {"name": "Imipenem", "R": 19, "S": 23},
        "MEM": {"name": "Meropenem", "R": 19, "S": 23},
        "DOR": {"name": "Doripenem", "R": 19, "S": 23},
        "CN":  {"name": "Gentamicin", "R": 12, "S": 15},
        "TOB": {"name": "Tobramycin", "R": 12, "S": 15},
        "AK":  {"name": "Amikacin", "R": 14, "S": 17},
        "CIP": {"name": "Ciprofloxacin", "R": 21, "S": 26},
        "LEV": {"name": "Levofloxacin", "R": 16, "S": 21},
        "SXT": {"name": "Trimethoprim/Sulfamethoxazole", "R": 10, "S": 16},
        "FOS": {"name": "Fosfomycin", "R": 12, "S": 16},
        "F":   {"name": "Nitrofurantoin", "R": 14, "S": 17}
    },
    "P.aeruginosa": {
        "PIP": {"name": "Piperacillin", "R": 14, "S": 21},
        "TZP": {"name": "Piperacillin/Tazobactam", "R": 14, "S": 21},
        "TIC": {"name": "Ticarcillin", "R": 15, "S": 24},
        "CAZ": {"name": "Ceftazidime", "R": 14, "S": 18},
        "FEP": {"name": "Cefepime", "R": 14, "S": 18},
        "ATM": {"name": "Aztreonam", "R": 15, "S": 22},
        "IPM": {"name": "Imipenem", "R": 15, "S": 19},
        "MEM": {"name": "Meropenem", "R": 15, "S": 19},
        "DOR": {"name": "Doripenem", "R": 15, "S": 19},
        "AK":  {"name": "Amikacin", "R": 14, "S": 17},
        "CN":  {"name": "Gentamicin", "R": 12, "S": 15},
        "TOB": {"name": "Tobramycin", "R": 12, "S": 15},
        "CIP": {"name": "Ciprofloxacin", "R": 18, "S": 25},
        "LEV": {"name": "Levofloxacin", "R": 14, "S": 22},
        "C/T": {"name": "Ceftolozane/Tazobactam", "R": 16, "S": 21},
        "CZA": {"name": "Ceftazidime/Avibactam", "R": 20, "S": 21},
        "FDC": {"name": "Cefiderocol", "R": 12, "S": 18}
    },
    "S.aureus": {
        "FOX": {"name": "Cefoxitin (MRSA Screen)", "R": 21, "S": 22},
        "P":   {"name": "Penicillin G", "R": 28, "S": 29},
        "AMP": {"name": "Ampicillin", "R": 28, "S": 29},
        "CPT": {"name": "Ceftaroline", "R": 23, "S": 26},
        "TEC": {"name": "Teicoplanin", "R": 10, "S": 14},
        "LZD": {"name": "Linezolid", "R": 20, "S": 21},
        "TZD": {"name": "Tedizolid", "R": 18, "S": 19},
        "E":   {"name": "Erythromycin", "R": 13, "S": 23},
        "CLR": {"name": "Clarithromycin", "R": 13, "S": 21},
        "AZM": {"name": "Azithromycin", "R": 13, "S": 21},
        "DA":  {"name": "Clindamycin", "R": 14, "S": 21},
        "TE":  {"name": "Tetracycline", "R": 14, "S": 19},
        "DO":  {"name": "Doxycycline", "R": 12, "S": 16},
        "CN":  {"name": "Gentamicin", "R": 12, "S": 15},
        "TOB": {"name": "Tobramycin", "R": 12, "S": 15},
        "AK":  {"name": "Amikacin", "R": 14, "S": 17},
        "CIP": {"name": "Ciprofloxacin", "R": 15, "S": 21},
        "LEV": {"name": "Levofloxacin", "R": 15, "S": 19},
        "MXF": {"name": "Moxifloxacin", "R": 20, "S": 24},
        "SXT": {"name": "Trimethoprim/Sulfamethoxazole", "R": 10, "S": 16},
        "QD":  {"name": "Quinupristin/Dalfopristin", "R": 15, "S": 19}
    },
    "B.subtilis": {
        "VAN": {"name": "Vancomycin (Proxy)", "R": 14, "S": 15},
        "CIP": {"name": "Ciprofloxacin (Proxy)", "R": 15, "S": 21},
        "CN":  {"name": "Gentamicin (Proxy)", "R": 12, "S": 15},
        "LZD": {"name": "Linezolid (Proxy)", "R": 20, "S": 21},
        "E":   {"name": "Erythromycin (Proxy)", "R": 13, "S": 23},
        "DA":  {"name": "Clindamycin (Proxy)", "R": 14, "S": 21}
    },
    "C.albicans": {
        "FLC": {"name": "Fluconazole (Antifungal)", "R": 14, "S": 19},
        "VRC": {"name": "Voriconazole (Antifungal)", "R": 13, "S": 17},
        "POS": {"name": "Posaconazole (Antifungal)", "R": 16, "S": 17},
        "CAS": {"name": "Caspofungin (Antifungal)", "R": 10, "S": 11},
        "MFG": {"name": "Micafungin (Antifungal)", "R": 19, "S": 20}
    }
}

def process_image(img_array, contrast, brightness, denoise):
    if denoise:
        img_array = cv2.medianBlur(img_array, 3)
    if contrast != 1.0 or brightness != 0:
        img_array = cv2.convertScaleAbs(img_array, alpha=contrast, beta=brightness)
    return img_array

# ==========================================
# 2. إنشاء التبويبات (Tabs)
# ==========================================
# التبويبات دي هتقسم الصفحة لنصين فوق بعض تختار بينهم
tab1, tab2 = st.tabs(["Colony Counter", "AST Analyzer"])

# ------------------------------------------
# التبويب الأول: العد (كودك القديم)
# ------------------------------------------
with tab1:
    st.markdown("<h3 style='text-align: center;'>Bacterial Colony Analysis and Counting</h3>", unsafe_allow_html=True)
    # حط كود زرار الرفع بتاع البكتيريا ونتائج الكشاف الخماسي والبواب هنا
    # st.file_uploader(...) 
    # دالة معالجة الصور


# الرفع المتعدد للصور
    uploaded_files = st.file_uploader("Upload Petri Dish Samples (JPG/PNG)", type=["jpg", "jpeg", "png"], accept_multiple_files=True)

    if uploaded_files:
        st.success(f"{len(uploaded_files)} samples loaded. Analyzing batch...")
        all_reports_data = []
        
        for uploaded_file in uploaded_files:
            with st.expander(f"Analysis Report: {uploaded_file.name}", expanded=True):
                
                try:
                    image = Image.open(uploaded_file).convert("RGB")
                    img_array = np.array(image)
                except Exception:
                    st.error(f"❌ Could not read image: {uploaded_file.name}. File may be corrupted or unsupported.")
                    continue
                
                img_array = process_image(img_array, contrast, brightness, denoise)
                processed_image = Image.fromarray(img_array)
                
                #  1. الموديل البواب يفحص الصورة أولاً
                gate_results = gatekeeper_model.predict(source=processed_image, imgsz=640, verbose=False)
                probs = gate_results[0].probs
                
                if probs is None:
                    st.error("❌ Gatekeeper model failed to classify. Ensure it is a Classification model.")
                    continue
                    
                top_class_id = probs.top1
                gate_decision = gate_results[0].names[top_class_id]
                
                if gate_decision == "TNTC":
                    # حالة النمو الكثيف
                    st.error("🚨 **Alert: Confluent Growth / TNTC detected.**")
                    
                    # فحص سريع لمعرفة النوع المكدس
                    detector_model.overrides['max_det'] = 1000
                    results = detector_model.predict(source=processed_image, conf=conf_threshold, iou=iou_threshold, imgsz=1024, augment=tta_mode, verbose=False)
                    
                    boxes = results[0].boxes
                    class_ids = boxes.cls.tolist()
                    names = results[0].names
                    
                    detected_species = set()
                    for obj_id in class_ids:
                        detected_species.add(names[int(obj_id)])
                        
                    species_text = ", ".join(detected_species) if detected_species else "Unknown (Requires Manual ID)"
                    
                    st.warning(f"**Detected Pathogen(s): {species_text}**")
                    st.info("The colonies in this sample are too numerous to be counted, but the system identified the pathogen.")
                    
                    # تسجيل النتيجة (5 بكتيريات)
                    # --- التعديل: استدعاء دالة الأدوية ---
                    recommended_drugs = get_clinical_recommendations(list(detected_species))
                    
                    # تسجيل النتيجة (5 بكتيريات + عمود الأدوية)
                    all_reports_data.append({
                        "Image Name": uploaded_file.name,
                        "S.aureus": "TNTC" if "S.aureus" in detected_species else "0",
                        "E.coli": "TNTC" if "E.coli" in detected_species else "0",
                        "P.aeruginosa": "TNTC" if "P.aeruginosa" in detected_species else "0",
                        "B.subtilis": "TNTC" if "B.subtilis" in detected_species else "0",
                        "C.albicans": "TNTC" if "C.albicans" in detected_species else "0",
                        "Total Colonies": "TNTC",
                        "Recommended AST Panel": recommended_drugs # العمود الجديد
                    })
                    
                    col1, col2 = st.columns([1.2, 1])
                    with col1:
                        st.image(processed_image, caption=f"TNTC Plate - Pathogen: {species_text}", width="stretch")
                    with col2:
                        st.metric("Total Colonies", "TNTC")
                        st.metric("Identified Pathogen", species_text)

                else:
                    # ✅ حالة الطبق السليم
                    st.success("✅ **Sample Countable. Proceeding with quantification...**")
                    
                    results = detector_model.predict(source=processed_image, conf=conf_threshold, iou=iou_threshold, imgsz=1024, augment=tta_mode, verbose=False)
                    
                    show_text = not hide_labels
                    res_image = results[0].plot(labels=show_text, conf=show_text, line_width=box_thickness, font_size=label_size, pil=True)
                    
                    boxes = results[0].boxes
                    class_ids = boxes.cls.tolist()
                    names = results[0].names
                    
                    counts = {'S.aureus': 0, 'E.coli': 0, 'P.aeruginosa': 0, 'B.subtilis': 0, 'C.albicans': 0}
                    for obj_id in class_ids:
                        class_name = names[int(obj_id)]
                        if class_name in counts:
                            counts[class_name] += 1
                        
                    total = sum(counts.values())
                    
                    # ==========================================
                    # 1. حالة الطبق الفاضي (No Growth)
                    # ==========================================
                    if total == 0:
                        st.info("🟢 **No Growth Detected.** The plate appears to be sterile or contains no identifiable target colonies.")
                        
                        all_reports_data.append({
                            "Image Name": uploaded_file.name,
                            "S.aureus": "0",
                            "E.coli": "0",
                            "P.aeruginosa": "0",
                            "B.subtilis": "0",
                            "C.albicans": "0",
                            "Total Colonies": "0",
                            "Recommended AST Panel": "Sterile Sample (No further testing required)"
                        })
                        
                        # بنعرض الصورة مرة واحدة بس هنا
                        st.image(res_image, caption="Sterile Plate Output", width="stretch")
                        
                    # ==========================================
                    # 2. حالة وجود بكتيريا
                    # ==========================================
                    else:
                        detected_in_plate = [name for name, count in counts.items() if count > 0]
                        recommended_drugs = get_clinical_recommendations(detected_in_plate)
                        
                        all_reports_data.append({
                            "Image Name": uploaded_file.name,
                            "S.aureus": counts['S.aureus'],
                            "E.coli": counts['E.coli'],
                            "P.aeruginosa": counts['P.aeruginosa'],
                            "B.subtilis": counts['B.subtilis'],
                            "C.albicans": counts['C.albicans'],
                            "Total Colonies": total,
                            "Recommended AST Panel": recommended_drugs
                        })
                        
                        # بنعرض الصورة مرة واحدة بس هنا متقسمة مع الأرقام
                        col1, col2 = st.columns([1.2, 1])
                        with col1:
                            # تبويبات عرض الصورة (الذكاء الاصطناعي vs الأصلية)
                            img_tab1, img_tab2 = st.tabs(["AI Vision", "Raw Image"])
                            with img_tab1:
                                st.image(res_image, caption="AI Vision Output", width="stretch")
                            with img_tab2:
                                st.image(processed_image, caption="Original Raw Image", width="stretch")
                        with col2:
                            st.metric("Total Colonies", total)
                            st.divider()
                            
                            m1, m2 = st.columns(2)
                            with m1:
                                st.metric("🟡 S. aureus", counts['S.aureus'])
                                st.metric("🔵 P. aeruginosa", counts['P.aeruginosa'])
                                st.metric("🟢 B. subtilis", counts['B.subtilis'])
                            with m2:
                                st.metric("🔴 E. coli", counts['E.coli'])
                                st.metric("🟣 C. albicans", counts['C.albicans'])
                                
                        # ==========================================
                        # جزء الترشيحات الطبية (Clinical Guidelines & Workflows)
                        # ==========================================
                        st.markdown("---")
                        st.markdown("#### 💊 Clinical Antibiotic Guidelines (CDSS)")
                        
                        for bacteria in detected_in_plate:
                            if bacteria in ANTIBIOTIC_GUIDE:
                                with st.expander(f"🩺 Treatment & Screening Protocol for {bacteria}", expanded=False):
                                    
                                    if "Workflow" in ANTIBIOTIC_GUIDE[bacteria]:
                                        st.warning(f"⚠️ **Clinical Screening Workflow for {bacteria}:**")
                                        for step, action in ANTIBIOTIC_GUIDE[bacteria]["Workflow"].items():
                                            st.markdown(f"**{step}:** {action}")
                                        st.markdown("---")
                                    
                                    if "Phenotypes" in ANTIBIOTIC_GUIDE[bacteria]:
                                        st.info("🧬 **Select the diagnosed phenotype based on the screening workflow above:**")
                                        phenotype_names = list(ANTIBIOTIC_GUIDE[bacteria]["Phenotypes"].keys())
                                        tabs = st.tabs(phenotype_names)
                                        
                                        for i, tab in enumerate(tabs):
                                            with tab:
                                                data = ANTIBIOTIC_GUIDE[bacteria]["Phenotypes"][phenotype_names[i]]
                                                col_s, col_v, col_r = st.columns(3)
                                                
                                                with col_s:
                                                    st.success("**✅ Sensitive (S):**")
                                                    for drug in data.get("✅ Sensitive (S)", []):
                                                        st.write(f"- {drug}")
                                                with col_v:
                                                    st.warning("**⚠️ Variable (V/I):**")
                                                    for drug in data.get("⚠️ Variable / Intermediate", []):
                                                        st.write(f"- {drug}")
                                                with col_r:
                                                    st.error("**❌ Resistant (R):**")
                                                    for drug in data.get("❌ Resistant (R)", []):
                                                        st.write(f"- {drug}")
                                                        
                                    elif "Recommended" in ANTIBIOTIC_GUIDE[bacteria]:
                                        col_rec, col_res = st.columns(2)
                                        with col_rec:
                                            st.success("**✅ Primary Panel (Test These):**")
                                            for family, drugs in ANTIBIOTIC_GUIDE[bacteria]["Recommended"].items():
                                                st.markdown(f"- **{family}:** {', '.join(drugs)}")
                                        with col_res:
                                            st.error("**❌ Inherent Resistance (Do Not Test):**")
                                            for family, drugs in ANTIBIOTIC_GUIDE[bacteria]["Resistant"].items():
                                                st.markdown(f"- **{family}:** {', '.join(drugs)}")
        # جزء تحميل تقرير الـ CSV الشامل
        if all_reports_data:
            st.markdown("---")
            st.subheader("Batch Processing Complete")
            
            df = pd.DataFrame(all_reports_data)
            csv = df.to_csv(index=False).encode('utf-8')
            
            st.download_button(
                label=f"⬇️ Download Combined CSV Report for {len(uploaded_files)} samples",
                data=csv,
                file_name="Bulk_CFU_Lab_Report.csv",
                mime="text/csv",
                use_container_width=True
            )

# ------------------------------------------
# التبويب الثاني: AST (الكود الجديد المتعدد)
# ------------------------------------------
# ------------------------------------------
# التبويب الثاني: AST (الكود الجديد المتنظم)
# ------------------------------------------
with tab2:
    st.markdown("<h3 style='text-align: center;'>Antibiotic Susceptibility Analysis (AST)</h3>", unsafe_allow_html=True)
    
    ast_files = st.file_uploader("Upload AST Plate Images (You may select multiple images at once)", type=["jpg", "png", "jpeg"], accept_multiple_files=True, key="ast_uploader")

    if ast_files:
        for idx, ast_file in enumerate(ast_files):
            st.markdown(f"#### 🧪 Sample Analysis #{idx + 1}: `{ast_file.name}`")
            
            # قراءة الصورة الحالية
            file_bytes = np.frombuffer(ast_file.getvalue(), dtype=np.uint8)
            img_bgr = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)
            
            if img_bgr is None:
                st.error(f"❌ Failed to decode image: `{ast_file.name}`. File may be corrupted.")
                continue
            
            # 👇 السطر السحري اللي هيشغل السايد بار على التبويب التاني 👇
            img_bgr = process_image(img_bgr, contrast, brightness, denoise)
                
            annotated_img = img_bgr.copy()
            
            # التحليل بالموديل
            with st.spinner(f"Analyzing {ast_file.name}..."):
                results = ast_model.predict(img_bgr, conf=conf_threshold, iou=iou_threshold, verbose=False)[0]
            
            names = results.names
            disks = []
            zones = []
            
            for box in results.boxes:
                cls_name = names[int(box.cls[0])]
                x_c, y_c, w, h = box.xywh[0].tolist()
                diameter_px = max(w, h)
                
                if cls_name == 'disk':
                    disks.append({'x': x_c, 'y': y_c, 'd_px': diameter_px})
                elif cls_name == 'zone':
                    zones.append({'x': x_c, 'y': y_c, 'd_px': diameter_px})
                    
            REAL_DISK_MM = 6.0
            measured_disks = []
            
            # الحسابات والرسم (إضافة أرقام تعريفية للأقراص)
            for i, disk in enumerate(disks):
                disk_id = i + 1 # رقم القرص (1, 2, 3...)
                
                if disk['d_px'] <= 0:
                    st.warning(f"⚠️ Disk #{disk_id}: Invalid detection (zero diameter). Skipping.")
                    continue
                    
                mm_per_pixel = REAL_DISK_MM / disk['d_px']
                matched_zone = None
                min_dist = float('inf')
                
                for zone in zones:
                    dist = math.hypot(disk['x'] - zone['x'], disk['y'] - zone['y'])
                    
                    # نخلي أقصى مسافة مسموحة هي ضعف قطر القرص عشان تغطي الهالات المسحوبة
                    max_allowed_dist = disk['d_px'] * 2.5 
                    
                    if dist < max_allowed_dist and dist < min_dist: # ✅ التعديل هنا
                        min_dist = dist
                        matched_zone = zone
                        
                center_x = int(disk['x'])
                center_y = int(disk['y'])
                
                if matched_zone:
                    zone_mm = matched_zone['d_px'] * mm_per_pixel
                    zone_radius_px = int(matched_zone['d_px'] / 2)
                    color = (255, 191, 0) # لون سماوي محايد للهالة
                    cv2.circle(annotated_img, (int(matched_zone['x']), int(matched_zone['y'])), zone_radius_px, color, 3)
                else:
                    zone_mm = 6.0
                    color = (0, 0, 255) # لون أحمر لو مفيش هالة
                    disk_radius_px = int(disk['d_px'] / 2)
                    cv2.circle(annotated_img, (center_x, center_y), disk_radius_px, color, 3)
                
                # كتابة رقم القرص (ID) بلون أصفر عشان يشد الانتباه
                id_text = f"#{disk_id}"
                font = cv2.FONT_HERSHEY_SIMPLEX
                cv2.putText(annotated_img, id_text, (center_x - 15, center_y - 10), font, 0.8, (0, 0, 0), 4) # ضل أسود
                cv2.putText(annotated_img, id_text, (center_x - 15, center_y - 10), font, 0.8, (0, 255, 255), 2) # لون أصفر
                
                # كتابة القطر بالمليمتر تحت الرقم بلون أبيض
                mm_text = f"{zone_mm:.1f}mm"
                cv2.putText(annotated_img, mm_text, (center_x - 25, center_y + 15), font, 0.5, (0, 0, 0), 3) # ضل أسود
                cv2.putText(annotated_img, mm_text, (center_x - 25, center_y + 15), font, 0.5, (255, 255, 255), 1) # لون أبيض
                
                # تخزين الداتا للواجهة التفاعلية
                measured_disks.append({'id': disk_id, 'zone_mm': zone_mm})
                
            # ==========================================
            # واجهة التشخيص التفاعلية (الشكل النظيف)
            # ==========================================
            with st.expander(f"Analysis Report & Interpretation: {ast_file.name}", expanded=True):
                st.success("✅ **Measurements Complete. Please select the bacteria and antibiotics.**")
                
                # 1. اختيار البكتيريا بالعرض كله فوق
                bacteria_options = ["Select Bacteria..."] + list(AST_BREAKPOINTS.keys())
                selected_bacteria = st.selectbox(f"Select diagnosed bacteria for the plate:", bacteria_options, key=f"bac_select_{idx}")
                st.markdown("---")
                
                # 2. تقسيم الشاشة نصين: الصورة على الشمال والجدول على اليمين
                col_img, col_ui = st.columns([1.2, 1.5]) # نسبة العرض (الصورة أصغر شوية من الجدول)
                
                with col_img:
                    # 1. تجهيز الألوان للصور
                    img_rgb = cv2.cvtColor(annotated_img, cv2.COLOR_BGR2RGB)
                    raw_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
                    
                    # 2. استخراج صورة الـ YOLO الخام (بالمربعات ونسب الثقة زي ما طلبت)
                    show_text = not hide_labels
                    yolo_img = results.plot(labels=show_text, conf=show_text, line_width=box_thickness, font_size=label_size, pil=True)
                    
                    # 3. عمل 3 تبويبات بدل 2
                    img_tab1, img_tab2, img_tab3 = st.tabs(["Measurements", "YOLO Boxes", "Raw Image"])
                    
                    with img_tab1:
                        st.image(img_rgb, caption="Clean UI: Measured Zones & Disk IDs", width="stretch")
                    with img_tab2:
                        st.image(yolo_img, caption="Deep Vision: YOLO Bounding Boxes & Confidence", width="stretch")
                    with img_tab3:
                        st.image(raw_rgb, caption="Original Raw Image", width="stretch")
                    
                with col_ui:
                    if selected_bacteria != "Select Bacteria...":
                        available_drugs = list(AST_BREAKPOINTS[selected_bacteria].keys())
                        drug_options = [f"{code} ({AST_BREAKPOINTS[selected_bacteria][code]['name']})" for code in available_drugs]
                        
                        st.markdown("#### 💊 Assign Antibiotics")
                        
                        report_data = []
                        all_selected = True
                        
                        # 1. الشكل القديم المريح (صفوف و Selectbox)
                        for disk_info in measured_disks:
                            c1, c2, c3 = st.columns([1, 2, 1.5])
                            zone_val = disk_info['zone_mm']
                            disk_id = f"#{disk_info['id']}"
                            
                            with c1:
                                st.markdown(f"<div style='text-align: center; margin-top: 10px;'><span style='color: #FFD700; font-weight: bold; font-size: 1.2em;'>{disk_id}</span><br><span style='color: #4CAF50;'>{zone_val:.1f} mm</span></div>", unsafe_allow_html=True)
                            
                            with c2:
                                selected_drug = st.selectbox(
                                    f"Select Drug", 
                                    ["Select Antibiotic..."] + drug_options, 
                                    key=f"drug_select_{idx}_{disk_info['id']}_{selected_bacteria}",
                                    label_visibility="collapsed"
                                )
                            
                            with c3:
                                if selected_drug == "Select Antibiotic...":
                                    all_selected = False
                                    status = "⏳ Waiting..."
                                    st.write("⏳ Waiting...")
                                    drug_val = "Not Selected"
                                else:
                                    drug_code = selected_drug.split(" ", 1)[0]
                                    breakpoints = AST_BREAKPOINTS[selected_bacteria].get(drug_code)
                                    
                                    if breakpoints:
                                        if zone_val >= breakpoints["S"]:
                                            status = "✅ Sensitive (S)"
                                            st.success(f"**✅ S**")
                                        elif zone_val <= breakpoints["R"]:
                                            status = "❌ Resistant (R)"
                                            st.error(f"**❌ R**")
                                        else:
                                            status = "⚠️ Intermediate (I)"
                                            st.warning(f"**⚠️ I**")
                                    else:
                                        status = "⚠️ Invalid"
                                        st.error("⚠️ Invalid")
                                        all_selected = False
                                        
                                    drug_val = selected_drug
                                    
                                report_data.append({
                                    "Disk Number": disk_id,
                                    "Antibiotic": drug_val,
                                    "Diameter (mm)": f"{zone_val:.1f}",
                                    "Clinical Status": status
                                })
                        
                        # 2. قسم التحميل وإصدار التقرير
                        st.divider()
                        st.markdown("#### 📄 Patient Report Export")
                        
                        # إدخال الاسم دايما موجود وثابت في الصفحة
                        patient_name = st.text_input("Patient Name (Optional):", placeholder="e.g., John Doe", key=f"patient_name_{idx}")

                        # تهيئة زرار الاعتماد
                        prep_key = f"prepare_files_{idx}"
                        if prep_key not in st.session_state:
                            st.session_state[prep_key] = False
                            
                        # الزرار دايما موجود، بس هيكون "مقفول" (disabled=True) لو لسه مخلصتش
                        if st.button("⚙️ Generate Files", key=f"btn_gen_{idx}", disabled=not all_selected, help="Select all antibiotics to unlock this button"):
                            st.session_state[prep_key] = True

                        # لو لسه مخلصش الاختيارات، نطلعله رسالة تفكره
                        if not all_selected:
                            st.info(f"⏳ Please assign antibiotics to all {len(measured_disks)} disks above to enable file generation.")
                        else:
                            # لو خلص وداس على الزرار بإيده
                            if st.session_state[prep_key]:
                                st.success("✅ Files generated successfully! You can download them below.")
                                
                                final_df = pd.DataFrame(report_data)
                                col_down1, col_down2 = st.columns(2)
                                
                                with col_down1:
                                    csv_data = final_df.to_csv(index=False).encode('utf-8')
                                    st.download_button(
                                        label="⬇️ Download CSV",
                                        data=csv_data,
                                        file_name=f"AST_Clinical_Report_{ast_file.name}.csv",
                                        mime="text/csv",
                                        key=f"download_csv_{idx}",
                                        use_container_width=True
                                    )
                                    
                                with col_down2:
                                    pdf_data = create_ast_pdf(patient_name, ast_file.name, selected_bacteria, report_data)
                                    st.download_button(
                                        label="📄 Download PDF Report",
                                        data=pdf_data,
                                        file_name=f"BactoVision_LabReport_{patient_name or 'Patient'}.pdf",
                                        mime="application/pdf",
                                        key=f"download_pdf_{idx}",
                                        use_container_width=True
                                    )